name: bump_version

on:
  workflow_dispatch:

jobs:
  bump_version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - id: compute_tag
        uses: craig-day/compute-tag@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_scheme: semantic

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
          architecture: x64

      - name: Compile
        run: |
          python -m pip install -e .
          python -m nuitka --onefile chirp.py --windows-onefile-tempdir --plugin-enable=multiprocessing --plugin-enable=pylint-warnings --windows-uac-admin --assume-yes-for-downloads --windows-icon-from-ico=.\assets\CISA_Logo.ico --msvc=14.2

      - name: Hash
        id: hash
        run: |
          Get-ChildItem -Recurse -Path @('chirp.exe', 'chirp.py', 'chirp\*.py') -Exclude "chirp.dist"| %{Get-FileHash $_ |  Export-Csv  -Path 'hashes.csv' -Append -NoTypeInformation} 2>&1 | Out-Null

      - name: Bundle
        run: |
          $compress = @{
          LiteralPath= ".\README.md", ".\chirp.exe", ".\indicators", "chirp.py", ".\chirp", "LICENSE", "setup.py"
          CompressionLevel = "Optimal"
          DestinationPath = ".\chirp.zip"
          }
          Compress-Archive @compress

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          release_name: ${{ steps.compute_tag.outputs.next_tag }}
          draft: true
          prerelease: false
          body: >
            Automatic release of ${{ steps.compute_tag.outputs.next_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Zip
        id: upload-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./chirp.zip
          asset_name: chirp.zip
          asset_content_type: application/zip

      - name: Upload Hashes
        id: upload-hashes
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./hashes.csv
          asset_name: hashes.csv
          asset_content_type: text/csv
